### ISSUE TITLE
Reference the official country documentation

### ISSUE THREAD

**Issue by SLourenco** [reducktion/socrates#58]
The algorithms from this library are specified by national authorities of each country.
For example, for Portugal, one can find the official documents in the Portuguese government [official website](https://www.autenticacao.gov.pt/documents/20126/115760/Valida%C3%A7%C3%A3o+de+N%C3%BAmero+de+Documento+do+Cart%C3%A3o+de+Cidad%C3%A3o.pdf/bdc4eb37-7316-3ff4-164a-f869382b7053).

You should add a link to the official document (and the date) you based your calculation on, either in the respective country file or somewhere in the documentation. I think this will be very helpful when using the library, either to identify possible bugs or to simply have additional documentation to check for a particular country.

**List of documentation links:**
- [Portugal](https://www.autenticacao.gov.pt/documents/20126/115760/Valida%C3%A7%C3%A3o+de+N%C3%BAmero+de+Documento+do+Cart%C3%A3o+de+Cidad%C3%A3o.pdf/bdc4eb37-7316-3ff4-164a-f869382b7053)
- [Spain](http://www.interior.gob.es/web/servicios-al-ciudadano/dni/calculo-del-digito-de-control-del-nif-nie)
- [Italy](http://www.dossier.net/utilities/codice-fiscale/decreto1974_2227.html)

**Comment by AlexOlival** [comment]
This is something we thought about since the initial concept of this package.
However, we soon found out that most countries have a very poor - or hard to find - official documentation, such that most algorithms were not found in any official sources.

@JoaoFSCruz what do you think about this? At first, we thought of even documenting how every ID roughly works.

**Comment by JoaoFSCruz** [comment]
Maybe we should specify what we based each country's implementation on. It might even help uncover mistakes. Although I no longer remember the sources I used.

**Comment by SLourenco** [comment]
Well, if it helps, I can add to this issue the ones that I find. I think official (government) links should be preferable, but any reference seems to be that it would be preferable to none.

- Portugal: https://www.autenticacao.gov.pt/documents/20126/115760/Valida%C3%A7%C3%A3o+de+N%C3%BAmero+de+Documento+do+Cart%C3%A3o+de+Cidad%C3%A3o.pdf/bdc4eb37-7316-3ff4-164a-f869382b7053
- Spain: http://www.interior.gob.es/web/servicios-al-ciudadano/dni/calculo-del-digito-de-control-del-nif-nie

**Comment by AlexOlival** [comment]
@SLourenco where do you feel this would make more sense? A markdown file, or a docblock in the Validation class itself?

**Comment by SLourenco** [comment]
I think either option is fine.

**Comment by SLourenco** [comment]
Links for the Italian documentation:

- Tax code validation is found in the Italy's Ministry of Finance Decree of 12/03/1974 n. 2227 ([online version](http://www.dossier.net/utilities/codice-fiscale/decreto1974_2227.html) and [wikipedia](https://en.wikipedia.org/wiki/Italian_fiscal_code))

- List of region codes in a [web archive](https://web.archive.org/web/20160819012136/http://www.agenziaentrate.gov.it/wps/wcm/connect/321b0500426a5e2492629bc065cef0e8/codicicatastali_comuni_29_11_2010.pdf?MOD=AJPERES&CACHEID=321b500426a5e2492629bc065cef0e8)

**Comment by SLourenco** [comment]
Documentation links for belgium were referenced in the java port:
https://github.com/reducktion/socrates-java/issues/32

* https://www.ibz.rrn.fgov.be/fileadmin/user_upload/nl/rr/instructies/IT-lijst/IT000_Rijksregisternummer.pdf
