### ISSUE TITLE
French special month codes

### ISSUE THREAD

**Issue by SLourenco** [reducktion/socrates#61]
Following this reference documentation (cited in wikipedia) there is the possibility of special digits for the month section of the french national identity card number:

> **6.3 3 ème composante : mois de naissance (2 chiffres)**
codification : de 01 (janvier) à 12 (décembre)
Les mois de naissance fictifs 20 à 30 ou 50 ou plus caractérisent le NIR  d'une personne inscrite aurépertoire  sur  la  base  d'une  pièce  d'état  civil  ne  mentionnant  pas  son  mois  de  naissance  (cf.précisions complémentaires).Les  mois  de  naissance  "pseudo-fictifs"  31  (janvier)  à  42  (décembre)  caractérisent  le  NIR  d'unepersonne  inscrite  au  répertoire  sur  la  base  d'une  pièce  d'état  civil  incomplète  mais  mentionnanttoutefois un mis de naissance.
from [Normalisation du numéro INSEEdes personnes physiques](http://resoo.org/docs/_docs/regles-numero-insee.pdf)

Which means (if google translate does not fail me) that the following options are available:

- 01 - 12: Representing the month of the year
- 20 - 30, 50: Indicating that the month of birth is **unknown**
- 31 - 42: The person has an incomplete civil status document, but their month of birth is **known**

It seems to me that the current code will fail with any of the _special_ digits:
```PHP
private function getDateOfBirth(string $id): Carbon
{
  $dateDigits = substr($id, 1, 4);
  [$year, $month] = str_split($dateDigits, 2);
  $currentYear = (int) now()->format('y');

  $year = (int) $year > $currentYear ? (int) $year + 1900 : (int) $year + 2000;

  return Carbon::createFromFormat('Y-m', "$year-$month");
}
```
The extraction should have the month of birth information, even with the 31-42 digits, and ideally not fail (rather be incomplete) on the 20-30 or 50 digits.

**Comment by JoaoFSCruz** [comment]
I had checked there were some nuances on the month but never really got into it and totally forgot about them. I'll get down to it as soon as possible. Thanks a lot!
