### ISSUE TITLE
Luxembourg ID validation

### ISSUE THREAD

**Issue by afbernardino** [reducktion/socrates#76]
According to [this documentation](https://www.oecd.org/tax/automatic-exchange/crs-implementation-and-assistance/tax-identification-numbers/Luxembourg-TIN.pdf) and this [wikipedia page](https://en.wikipedia.org/wiki/National_identification_number#Luxembourg), the Luxembourg ID validation is performed by:
1. computing check digit, based on the Luhn Algorithm and the first 11 digits of the ID, and compare it with the 12nd digit of the ID.
2. computing check digit, based on the Verhoeff Algorithm and the first 11 digits of the ID, and compare it with the 13rd digit of the ID.

This is not what is happening in:
https://github.com/reducktion/socrates/blob/b55f58117a171df1b8180183479a27c29cdd496a/src/Core/Luxembourg/LuxembourgIdValidator.php#L29

I've been trying to get some real ID's to test it, but I wasn't successful.

Can you check?

**Comment by AlexOlival** [comment]
Sounds like we're dealing with either two different IDs altogether or a new version of the ID number 🧐

I think our best bet is to ask a national

**Comment by AlexOlival** [comment]
So I asked a friend and it seems we have ourselves a pickle. According to her, the ID format is "AB1CDEF23".

What we have is the social security number. Seems like it's Google time for this one again @JoaoFSCruz... 🙁

**Comment by JoaoFSCruz** [comment]
Well, I guess it is 😅 

If I find anything I'll post it here so we can be on the same page.
