### ISSUE TITLE
[v1.3.0] Implement Chile ID 🇨🇱 (RUT) validator

### ISSUE THREAD

**Issue by gheleri** [reducktion/socrates#79]
- Implement the Chile ID validator based on the [description](https://es.wikipedia.org/wiki/Rol_%C3%9Anico_Tributario) and [algorithm](https://es.wikipedia.org/wiki/Anexo:Implementaciones_para_algoritmo_de_rut) available on Wikipedia
- Write tests
@JoaoFSCruz Would it be possible to relate the issue to the hacktoberfest label? xD

**Comment by JoaoFSCruz** [comment]
Shoot a PR with code. Everything is set up to start 😉 

![image](https://user-images.githubusercontent.com/26048679/95501728-a73ad480-09a0-11eb-967f-72e48df6d21f.png)

**Comment by AlexOlival** [comment]
Closed by #81
