### ISSUE TITLE
[v1.3.0] Incorrect ID validation for Belgium.

### ISSUE THREAD

**Issue by YvesBos** [reducktion/socrates#82]
Related to #75, I see some problems with the current implementation:

- It does not allow 00 as day or 00 as month while the docs specify that it is allowed for people whose day/month of birth was unknown at the time of registration.
- Digits 7-9 represent a sequence number that ranges from 001 to 998 (both inclusive) so values 000 and 999 are invalid. The current implementation does not seem to check this.

See https://github.com/reducktion/socrates-java/pull/36/files for an implementation in the Java fork that does take these things into account.

I'm up for fixing it if you want, please confirm.

**Comment by AlexOlival** [comment]
Hi, please refer to #76
It seems like there is a problem with the "ID" we're using itself 😅

**Comment by YvesBos** [comment]
This specific issue is unrelated, the Belgian National Number (ID) is used on both the social security card and the official identity card. 

The ID you're using is the correct one for Belgium. The validation logic as is just does not take into account the 2 things I rased in the issue.

**Comment by AlexOlival** [comment]
@YvesBos apologies... it was a long day and I was stuck in Luxembourg mode.

By all means, if you can put a PR up, please do!
Target the 1.2 branch please

**Comment by AlexOlival** [comment]
@YvesBos I have fixed the branch name because it was erroneously targetting a tag.
Please change the merge target to release-1.3.0

**Comment by AlexOlival** [comment]
Fixed by #91
