### ISSUE TITLE
Implement South Africa 🇿🇦

### ISSUE THREAD

**Issue by gheleri** [reducktion/socrates#87]
- Implement the South Africa ID validator, extractor and unit tests. 
- There're info available on [Wikipedia](https://en.wikipedia.org/wiki/South_African_identity_card) and [Government Site ](https://www.westerncape.gov.za/general-publication/decoding-your-south-african-id-number-0)

**Comment by AlexOlival** [comment]
I'm going to go ahead and close this for now - we're focusing on the Americas and the remaining European countries at the moment.

Will reopen later on :+1:

**Comment by gheleri** [comment]
No problem
